### PR TITLE
Closes #25  display messages if MetricID doesn't match results and metrics dataframe

### LINKED ISSUE #25: Bugfix: `MakeBounds` should exit gracefully if a mismatch between metric IDs in `results` and `metrics` is detected.
## Steps to Reproduce

1.
2.
3.
4.

### PR DESCRIPTION
**Pull request by zdz2101**

### CODE REVIEW

File: R/MakeBounds.R [hunk 1]
```diff
@@ -70,35 +70,47 @@ MakeBounds <- function(
...
-        dfBounds <- Analyze_NormalApprox_PredictBounds(
-          dfResult,
-          strType = lMetric$AnalysisType %||% "binary",
-          vThreshold = vThreshold
-        ) %>%
-          mutate(MetricID = strMetric) %>%
-          mutate(StudyID = strStudyID) %>%
-          mutate(SnapshotDate = dSnapshotDate)
-      }
+      if (!(strMetric %in% dfMetrics$MetricID)) {
```
Comment (lauramaxwell) [inline R/MakeBounds.R:82]: should we collect all missing MetricIDs and print them all in the warning message, to reduce the need for the user to do iterative runs to find all missing Metrics?

**Review by lauramaxwell — COMMENTED** [review]
Looks good. One possible edit to make re: the content of the message. See in-line comment for details

File: R/MakeBounds.R (hunk 1 above)
Comment (zdz2101) [reply R/MakeBounds.R:82]: moved the warning to before the map call, and modified test to demo messaging

**Review by lauramaxwell — APPROVED** [review]
looks good!
